---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: storage
      mountPath: /usr/share/nginx/html  # El directorio en el contenedor donde el volumen será montado
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: pvc-example  # Usamos el PVC que hemos creado
