name: Build_chatbot

on:
  push:
    branches:
      - main        # Define la rama en la que quieres que se ejecute (por ejemplo, "main")
    paths:
      - 'docker_images/node_dia_31/**'  # Reemplaza con la ruta de la carpeta que te interesa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear repositorio
        uses: actions/checkout@v3
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
          aws-region: eu-west-2

      - name: Loguearse en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'
          registry-type: private

      - name: Construir imagen Docker
        run: |
          cd docker_images/node_dia_31
          docker build --no-cache -t chat-bot .
      
      - name: Etiquetar imagen Docker
        run: |
          docker tag chat-bot:latest 248189943700.dkr.ecr.eu-west-2.amazonaws.com/stb-my-ecr-repo:chat-bot

      - name: Push de imagen a ECR
        run: |
          docker push 248189943700.dkr.ecr.eu-west-2.amazonaws.com/stb-my-ecr-repo:chat-bot
