name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Terraform
      run: |
        sudo apt-get update
        sudo apt-get install -y terraform

    - name: Terraform Init
      run: terraform init
      working-directory: ./ # Ajusta el directorio si es necesario

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./ # Ajusta el directorio si es necesario

    - name: Deploy with Terraform
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} # Añadir el token de sesión
      working-directory: ./ # Ajusta el directorio si es necesario
